version: '2.1'
volumes:
    config:
services:
  # mariadb:
  #   image: "lscr.io/linuxserver/mariadb:arm32v7-10.6.12-r0-ls91"
  #   container_name: mariadb
  #   restart: unless-stopped
  #   environment:
  #     - TZ=Europe/Paris # Specify a timezone to use EG Europe/London.
  #     - PUID=1000 # for UserID
  #     - PGID=1000 # for GroupID
  #     - MYSQL_USER=user # This user will have superuser access to the database specified by MYSQL_DATABASE (do not use root here).
  #     - MYSQL_ROOT_PASSWORD=Serv1991-1991chocolat-praline-menthe # Set this to root password for installation (minimum 4 characters).
  #     - MYSQL_PASSWORD=Serv1991-1991chocolat-praline-menthe # Set this to the password you want to use for you MYSQL_USER (minimum 4 characters).
  #     - MYSQL_DATABASE=freepbx # Specify the name of a database to be created on image startup.
  #   ports:
  #     - 3306:3306/tcp 
  # freepbx:
  #   image: "epandi/asterisk-freepbx-arm:17.15-latest"
  #   container_name: freepbx
  #   restart: always
  #   environment:
  #     - DB_EMBEDDED=TRUE
  #     # - DB_HOST=mariadb
  #     # - DB_PORT=3306
  #     # - DB_NAME=freepbx
  #     # - DB_USER=user
  #     # - DB_PASS=Serv1991-1991chocolat-praline-menthe
  #     - TIMEZONE=Europe/Paris
  #     # - ENABLE_FAIL2BAN=TRUE
  #     # - ENABLE_FOP=FALSE
  #     # - ENABLE_SSL=FALSE
  #     # - ENABLE_XMPP=FALSE
  #     # - ENABLE_VM_TRANSCRIBE=FALSE
  #     - RTP_START=18000
  #     - RTP_FINISH=18100
  #   ports:
  #     - 80:80
  #     - 5060:5060/udp
  #     - 5160:5160/udp
  #     - 18000-18100:18000-18100/udp
  #    #### Flash Operator Panel
  #     - 4445:4445
  #   network_mode: "bridge"
  #   ### These final lines are for Fail2ban. If you don't want, comment and also add ENABLE_FAIL2BAN=FALSE to your environment
  #   # cap_add:
  #   #   - NET_ADMIN
  #   # privileged: true

  freepbx-app:
    container_name: freepbx-app
    image: epandi/asterisk-freepbx-arm:17.15-latest
    ports:
     #### If you aren't using a reverse proxy
      - 80:80
     #### If you want SSL Support and not using a reverse proxy
      - 443:443
      - 5060:5060/udp
      - 5160:5160/udp
      - 18000-18100:18000-18100/udp
     #### Flash Operator Panel
      - 4445:4445
    volumes:
      - /home/pi/Docker/asterisk17/certs:/certs
      - /home/pi/Docker/asterisk17/data:/data
      - /home/pi/Docker/asterisk17/logs:/var/log
      - /home/pi/Docker/asterisk17/data/www:/var/www/html
     ### Only Enable this option below if you set DB_EMBEDDED=TRUE
      - /home/pi/Docker/asterisk17/db:/var/lib/mysql
     ### You can drop custom files overtop of the image if you have made modifications to modules/css/whatever - Use with care
     #- ./assets/custom:/assets/custom

    environment:
      - VIRTUAL_HOST=asterisk.local
      - VIRTUAL_NETWORK=nginx-proxy
     ### If you want to connect to the SSL Enabled Container
     #- VIRTUAL_PORT=443
     #- VIRTUAL_PROTO=https
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=hostname.example.com
      - LETSENCRYPT_EMAIL=email@example.com

      - ZABBIX_HOSTNAME=freepbx-app

      - RTP_START=18000
      - RTP_FINISH=18100

     ## Use for External MySQL Server
      - DB_EMBEDDED=TRUE

     ### These are only necessary if DB_EMBEDDED=FALSE
     # - DB_HOST=freepbx-db
     # - DB_PORT=3306
     # - DB_NAME=asterisk
     # - DB_USER=asterisk
     # - DB_PASS=asteriskpass

     ### If you are using TLS Support for Apache to listen on 443 in the container drop them in /certs and set these:
     #- TLS_CERT=cert.pem
     #- TLS_KEY=key.pem

    restart: always
    network_mode: "bridge"

    ### These final lines are for Fail2ban. If you don't want, comment and also add ENABLE_FAIL2BAN=FALSE to your environment
    cap_add:
      - NET_ADMIN
    privileged: true